[build]
  functions = "functions"
  command = "npm start"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/commonTask/*"
  status = 200
  to = "/.netlify/functions/index/:splat"