[build]
  functions = "netlify/functions"
  command = "echo Building functions"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  status = 200
  from = "/commomTask/*"
  to = "/.netlify/functions/index/:splat"